version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tattoo
      POSTGRES_PASSWORD: tattoo123
      POSTGRES_DB: tattoo_studio
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 